version: '3.8'

services:
  # Express backend server
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    container_name: template-doctor-server
    ports:
      - "3001:3001"  # Express server (NOT 7071 - that's Azure Functions)
    environment:
      - NODE_ENV=production
      - PORT=3001
      # GitHub OAuth
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      # GitHub Tokens
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GH_WORKFLOW_TOKEN=${GH_WORKFLOW_TOKEN}
      - GITHUB_TOKEN_ANALYZER=${GITHUB_TOKEN_ANALYZER}
      # Configuration
      - DEFAULT_RULE_SET=${DEFAULT_RULE_SET:-dod}
      - REQUIRE_AUTH_FOR_RESULTS=${REQUIRE_AUTH_FOR_RESULTS:-true}
      - AUTO_SAVE_RESULTS=${AUTO_SAVE_RESULTS:-false}
      - ARCHIVE_ENABLED=${ARCHIVE_ENABLED:-false}
      - ARCHIVE_COLLECTION=${ARCHIVE_COLLECTION:-aigallery}
      - DISPATCH_TARGET_REPO=${DISPATCH_TARGET_REPO}
      - ISSUE_AI_ENABLED=${ISSUE_AI_ENABLED:-false}
      - DEPRECATED_MODELS=${DEPRECATED_MODELS}
      # Backend URL (empty for same-origin)
      - TD_BACKEND_BASE_URL=
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - template-doctor

  # Vite frontend app
  app:
    build:
      context: .
      dockerfile: packages/app/Dockerfile
    container_name: template-doctor-app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:3001
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - template-doctor

networks:
  template-doctor:
    driver: bridge
